compatibility_date = "2023-10-30"
main = "src/index.ts"
name = "quisido-csp-dev"
tsconfig = "./tsconfig.json"

analytics_engine_datasets = [
  { binding = "PRIVATE_DATASET", dataset = "CSP_PRIVATE_DEV" },
  { binding = "PUBLIC_DATASET", dataset = "CSP_PUBLIC_DEV" },
  { binding = "USAGE", dataset = "USAGE_DEV" },
]

d1_databases = [
  { binding = "CSP_DB", database_id = "CSP", database_name = "csp-dev" },
]

[dev]
local_protocol = "https"
port = 6586              # parseInt('csp', 36) % 9999

##############
# Production #
##############

[env.production]
name = "quisido-csp"

analytics_engine_datasets = [
  { binding = "PRIVATE_DATASET", dataset = "CSP_PRIVATE" },
  { binding = "PUBLIC_DATASET", dataset = "CSP_PUBLIC" },
  { binding = "USAGE", dataset = "USAGE" },
]

d1_databases = [
  { binding = "CSP_DB", database_id = "2ea99634-ee39-491d-94d9-f8e688d1cb92", database_name = "csp", preview_database_id = "a5299acf-42a8-47bb-95e7-c062bc772b48" },
]

[env.production.vars]
ENVIRONMENT_NAME = "production"

###########
# Staging #
###########

[env.staging]
name = "quisido-csp-staging"
workers_dev = true

analytics_engine_datasets = [
  { binding = "PRIVATE_DATASET", dataset = "CSP_PRIVATE_STAGING" },
  { binding = "PUBLIC_DATASET", dataset = "CSP_PUBLIC_STAGING" },
  { binding = "USAGE", dataset = "USAGE_STAGING" },
]

d1_databases = [
  { binding = "CSP_DB", database_id = "a5299acf-42a8-47bb-95e7-c062bc772b48", database_name = "csp-staging" },
]

[env.staging.vars]
ENVIRONMENT_NAME = "staging"

[placement]
mode = "smart"
